-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity myproject_relu_array_ap_fixed_6u_array_ap_ufixed_8_2_4_0_0_6u_relu_config4_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    layer2_out_dout : IN STD_LOGIC_VECTOR (47 downto 0);
    layer2_out_num_data_valid : IN STD_LOGIC_VECTOR (11 downto 0);
    layer2_out_fifo_cap : IN STD_LOGIC_VECTOR (11 downto 0);
    layer2_out_empty_n : IN STD_LOGIC;
    layer2_out_read : OUT STD_LOGIC;
    layer4_out_din : OUT STD_LOGIC_VECTOR (47 downto 0);
    layer4_out_num_data_valid : IN STD_LOGIC_VECTOR (11 downto 0);
    layer4_out_fifo_cap : IN STD_LOGIC_VECTOR (11 downto 0);
    layer4_out_full_n : IN STD_LOGIC;
    layer4_out_write : OUT STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC );
end;


architecture behav of myproject_relu_array_ap_fixed_6u_array_ap_ufixed_8_2_4_0_0_6u_relu_config4_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv11_790 : STD_LOGIC_VECTOR (10 downto 0) := "11110010000";
    constant ap_const_lv11_1 : STD_LOGIC_VECTOR (10 downto 0) := "00000000001";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_27 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100111";
    constant ap_const_lv32_28 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101000";
    constant ap_const_lv32_2F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101111";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001110";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_16 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010110";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_1E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011110";
    constant ap_const_lv32_26 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100110";
    constant ap_const_lv32_2E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101110";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";

attribute shreg_extract : string;
    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal internal_ap_ready : STD_LOGIC;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln41_fu_101_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal layer2_out_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal layer4_out_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal out_data_data_fu_232_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal out_data_data_reg_356 : STD_LOGIC_VECTOR (6 downto 0);
    signal out_data_data_15_fu_246_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal out_data_data_15_reg_361 : STD_LOGIC_VECTOR (6 downto 0);
    signal out_data_data_16_fu_260_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal out_data_data_16_reg_366 : STD_LOGIC_VECTOR (6 downto 0);
    signal out_data_data_18_fu_274_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal out_data_data_18_reg_371 : STD_LOGIC_VECTOR (6 downto 0);
    signal out_data_data_19_fu_288_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal out_data_data_19_reg_376 : STD_LOGIC_VECTOR (6 downto 0);
    signal out_data_data_21_fu_302_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal out_data_data_21_reg_381 : STD_LOGIC_VECTOR (6 downto 0);
    signal i_fu_76 : STD_LOGIC_VECTOR (10 downto 0);
    signal i_2_fu_107_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_i_1 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal out_data_data_22_fu_118_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln1649_fu_226_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln45_fu_122_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal in_data_data_fu_146_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln1649_98_fu_240_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln44_s_fu_156_p4 : STD_LOGIC_VECTOR (6 downto 0);
    signal out_data_data_23_fu_166_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln1649_99_fu_254_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln45_4_fu_176_p4 : STD_LOGIC_VECTOR (6 downto 0);
    signal in_data_data_15_fu_186_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln1649_100_fu_268_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln44_48_fu_196_p4 : STD_LOGIC_VECTOR (6 downto 0);
    signal out_data_data_24_fu_126_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln1649_101_fu_282_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln45_5_fu_206_p4 : STD_LOGIC_VECTOR (6 downto 0);
    signal in_data_data_16_fu_136_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln1649_102_fu_296_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln44_49_fu_216_p4 : STD_LOGIC_VECTOR (6 downto 0);
    signal zext_ln45_2_fu_322_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln51_48_fu_319_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln45_1_fu_316_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln51_fu_313_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln45_fu_310_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal or_ln57_s_fu_325_p7 : STD_LOGIC_VECTOR (46 downto 0);
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_condition_122 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component myproject_flow_control_loop_pipe IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC;
        ap_continue : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_U : component myproject_flow_control_loop_pipe
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => real_start,
        ap_ready => internal_ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int,
        ap_continue => ap_continue);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((real_start = ap_const_logic_1) and (internal_ap_ready = ap_const_logic_0))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    i_fu_76_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_122)) then
                if ((icmp_ln41_fu_101_p2 = ap_const_lv1_0)) then 
                    i_fu_76 <= i_2_fu_107_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    i_fu_76 <= ap_const_lv11_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                out_data_data_15_reg_361 <= out_data_data_15_fu_246_p3;
                out_data_data_16_reg_366 <= out_data_data_16_fu_260_p3;
                out_data_data_18_reg_371 <= out_data_data_18_fu_274_p3;
                out_data_data_19_reg_376 <= out_data_data_19_fu_288_p3;
                out_data_data_21_reg_381 <= out_data_data_21_fu_302_p3;
                out_data_data_reg_356 <= out_data_data_fu_232_p3;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_done_reg, layer2_out_empty_n, layer4_out_full_n, ap_start_int)
    begin
                ap_block_pp0_stage0_01001 <= ((ap_done_reg = ap_const_logic_1) or ((layer4_out_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1)) or ((layer2_out_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)) or ((ap_done_reg = ap_const_logic_1) and (ap_start_int = ap_const_logic_1)));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_done_reg, layer2_out_empty_n, layer4_out_full_n, ap_start_int)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_done_reg = ap_const_logic_1) or ((layer4_out_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1)) or ((layer2_out_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)) or ((ap_done_reg = ap_const_logic_1) and (ap_start_int = ap_const_logic_1)));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_done_reg, layer2_out_empty_n, layer4_out_full_n, ap_start_int)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_done_reg = ap_const_logic_1) or ((layer4_out_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1)) or ((layer2_out_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)) or ((ap_done_reg = ap_const_logic_1) and (ap_start_int = ap_const_logic_1)));
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(ap_done_reg)
    begin
                ap_block_state1_pp0_stage0_iter0 <= (ap_done_reg = ap_const_logic_1);
    end process;


    ap_block_state2_pp0_stage0_iter1_assign_proc : process(layer2_out_empty_n)
    begin
                ap_block_state2_pp0_stage0_iter1 <= (layer2_out_empty_n = ap_const_logic_0);
    end process;


    ap_block_state3_pp0_stage0_iter2_assign_proc : process(layer4_out_full_n)
    begin
                ap_block_state3_pp0_stage0_iter2 <= (layer4_out_full_n = ap_const_logic_0);
    end process;


    ap_condition_122_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_start_int)
    begin
                ap_condition_122 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, icmp_ln41_fu_101_p2, ap_start_int)
    begin
        if (((icmp_ln41_fu_101_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_done_reg, ap_block_pp0_stage0_subdone, ap_loop_exit_ready_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= internal_ap_ready;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i_1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, i_fu_76, ap_loop_init, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_i_1 <= ap_const_lv11_0;
        else 
            ap_sig_allocacmp_i_1 <= i_fu_76;
        end if; 
    end process;

    i_2_fu_107_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i_1) + unsigned(ap_const_lv11_1));
    icmp_ln1649_100_fu_268_p2 <= "1" when (signed(in_data_data_15_fu_186_p4) > signed(ap_const_lv8_0)) else "0";
    icmp_ln1649_101_fu_282_p2 <= "1" when (signed(out_data_data_24_fu_126_p4) > signed(ap_const_lv8_0)) else "0";
    icmp_ln1649_102_fu_296_p2 <= "1" when (signed(in_data_data_16_fu_136_p4) > signed(ap_const_lv8_0)) else "0";
    icmp_ln1649_98_fu_240_p2 <= "1" when (signed(in_data_data_fu_146_p4) > signed(ap_const_lv8_0)) else "0";
    icmp_ln1649_99_fu_254_p2 <= "1" when (signed(out_data_data_23_fu_166_p4) > signed(ap_const_lv8_0)) else "0";
    icmp_ln1649_fu_226_p2 <= "1" when (signed(out_data_data_22_fu_118_p1) > signed(ap_const_lv8_0)) else "0";
    icmp_ln41_fu_101_p2 <= "1" when (ap_sig_allocacmp_i_1 = ap_const_lv11_790) else "0";
    in_data_data_15_fu_186_p4 <= layer2_out_dout(31 downto 24);
    in_data_data_16_fu_136_p4 <= layer2_out_dout(47 downto 40);
    in_data_data_fu_146_p4 <= layer2_out_dout(15 downto 8);

    layer2_out_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, layer2_out_empty_n, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            layer2_out_blk_n <= layer2_out_empty_n;
        else 
            layer2_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    layer2_out_read_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            layer2_out_read <= ap_const_logic_1;
        else 
            layer2_out_read <= ap_const_logic_0;
        end if; 
    end process;


    layer4_out_blk_n_assign_proc : process(ap_enable_reg_pp0_iter2, layer4_out_full_n, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            layer4_out_blk_n <= layer4_out_full_n;
        else 
            layer4_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    layer4_out_din <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln57_s_fu_325_p7),48));

    layer4_out_write_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            layer4_out_write <= ap_const_logic_1;
        else 
            layer4_out_write <= ap_const_logic_0;
        end if; 
    end process;

    or_ln57_s_fu_325_p7 <= (((((out_data_data_21_reg_381 & zext_ln45_2_fu_322_p1) & zext_ln51_48_fu_319_p1) & zext_ln45_1_fu_316_p1) & zext_ln51_fu_313_p1) & zext_ln45_fu_310_p1);
    out_data_data_15_fu_246_p3 <= 
        trunc_ln44_s_fu_156_p4 when (icmp_ln1649_98_fu_240_p2(0) = '1') else 
        ap_const_lv7_0;
    out_data_data_16_fu_260_p3 <= 
        trunc_ln45_4_fu_176_p4 when (icmp_ln1649_99_fu_254_p2(0) = '1') else 
        ap_const_lv7_0;
    out_data_data_18_fu_274_p3 <= 
        trunc_ln44_48_fu_196_p4 when (icmp_ln1649_100_fu_268_p2(0) = '1') else 
        ap_const_lv7_0;
    out_data_data_19_fu_288_p3 <= 
        trunc_ln45_5_fu_206_p4 when (icmp_ln1649_101_fu_282_p2(0) = '1') else 
        ap_const_lv7_0;
    out_data_data_21_fu_302_p3 <= 
        trunc_ln44_49_fu_216_p4 when (icmp_ln1649_102_fu_296_p2(0) = '1') else 
        ap_const_lv7_0;
    out_data_data_22_fu_118_p1 <= layer2_out_dout(8 - 1 downto 0);
    out_data_data_23_fu_166_p4 <= layer2_out_dout(23 downto 16);
    out_data_data_24_fu_126_p4 <= layer2_out_dout(39 downto 32);
    out_data_data_fu_232_p3 <= 
        trunc_ln45_fu_122_p1 when (icmp_ln1649_fu_226_p2(0) = '1') else 
        ap_const_lv7_0;

    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_full_n = ap_const_logic_0) and (start_once_reg = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;

    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((real_start = ap_const_logic_1) and (start_once_reg = ap_const_logic_0))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;

    trunc_ln44_48_fu_196_p4 <= layer2_out_dout(30 downto 24);
    trunc_ln44_49_fu_216_p4 <= layer2_out_dout(46 downto 40);
    trunc_ln44_s_fu_156_p4 <= layer2_out_dout(14 downto 8);
    trunc_ln45_4_fu_176_p4 <= layer2_out_dout(22 downto 16);
    trunc_ln45_5_fu_206_p4 <= layer2_out_dout(38 downto 32);
    trunc_ln45_fu_122_p1 <= layer2_out_dout(7 - 1 downto 0);
    zext_ln45_1_fu_316_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(out_data_data_16_reg_366),8));
    zext_ln45_2_fu_322_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(out_data_data_19_reg_376),8));
    zext_ln45_fu_310_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(out_data_data_reg_356),8));
    zext_ln51_48_fu_319_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(out_data_data_18_reg_371),8));
    zext_ln51_fu_313_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(out_data_data_15_reg_361),8));
end behav;
